### ISSUE TITLE
rsync IPv6 error

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/ethsnap#3]
Originally reported by @starzou 

    just@test:~# rsync --archive --delete --compress rsync://ethsnap.com/main/ .ethereum/chaindata rsync: 
    failed to connect to ethsnap.com (66.228.43.225): No route to host (113) 
    rsync: failed to connect to ethsnap.com (2605:2700:0:3:a800:ff:fe61:3053): Connection timed out (110) 
    rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

I'll try and look into this tonight, thanks for the report.

**Comment by starzou** [comment]
It's still not working.

```
just@test:~# rsync --archive --delete --compress --partial --recursive rsync://ethsnap.com/main/ .ethereum/geth/chaindata/
rsync: failed to connect to ethsnap.com (66.228.43.225): No route to host (113)
rsync: failed to connect to ethsnap.com (2605:2700:0:3:a800:ff:fe61:3053): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
```

**Using rsync is better than download archive file.**

We need to fix it.

**Comment by mikeshultz** [comment]
Thanks for the report.  This has been fixed.

Also, FYI, the node is resyncing right now so it does not have the full blockchain yet.  Will probably take an hour or two.

**Comment by starzou** [comment]
It is working fine right now.
Thank you very much.

Tips: best way to sync files:
```
rsync --archive --delete --update --existing --compress --partial --recursive rsync://ethsnap.com/main/ .ethereum/geth/chaindata/
```


@mikeshultz How large is the chaindata folder?

**Comment by mikeshultz** [comment]
Roughly 50GB.
